name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs once every week, on Sunday at 00:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC_JzGeCHnGFHLFWynzX4zhA
          max_videos: 3
